name: Deploy Scrapper API

on:
  push:
    branches:
      - main # triggers deployment on push to main branchjj

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Starting deployment on VM..."
            cd /home/khumalothato56/scrapper || exit 1
            ./deploy.sh
            echo "Deployment script executed."
