name: Deploy Scrapper API on Push to Develop

on:
  push:
    branches:
      - main  # or develop if that's your actual branchjjjj

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VM via SSH
        run: |
          echo "Starting deployment on VM..."

          # Add your SSH private key temporarily
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # SSH into the VM and run the deploy script
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} \
          "cd /home/khumalothato56/scrapper && ./deploy.sh"

          echo "Deployment script executed."
